const THREE = window.THREE;

export const SKY_COLOR = 0x87ceeb;

let wasmSkyModule;
let wasmSkyReady = false;
const WASM_MODULE_CANDIDATES = [
    './pkg/bevy_sky_gradient.js',
    './bevy_sky_gradient.js',
];

async function findWasmModuleUrl() {
    for (const relativePath of WASM_MODULE_CANDIDATES) {
        const url = new URL(relativePath, import.meta.url);
        try {
            const response = await fetch(url, { method: 'GET', cache: 'no-store' });
            if (response.ok) return url.href;
        } catch (_error) {
            // keep trying next candidate
        }
    }
    return null;
}

async function ensureWasmSkyLoaded() {
    if (wasmSkyReady) return wasmSkyModule;
    try {
        const moduleUrl = await findWasmModuleUrl();
        if (!moduleUrl) {
            wasmSkyReady = true;
            wasmSkyModule = null;
            return null;
        }
        // Generated by wasm-pack / wasm-bindgen for src/sky crate.
        const module = await import(moduleUrl);
        if (typeof module.default === 'function') {
            await module.default();
        }
        wasmSkyModule = module;
        wasmSkyReady = true;
        return wasmSkyModule;
    } catch (_error) {
        wasmSkyReady = true;
        wasmSkyModule = null;
        return null;
    }
}

export function applySkyAtmosphere(scene) {
    scene.background = new THREE.Color(SKY_COLOR);
    scene.fog = new THREE.Fog(SKY_COLOR, 20, 60);

    ensureWasmSkyLoaded();

    return {
        update(timeSeconds) {
            if (!wasmSkyModule || typeof wasmSkyModule.sky_color_hex !== 'function') return;
            const nextHex = wasmSkyModule.sky_color_hex(timeSeconds);
            scene.background.setHex(nextHex);
            scene.fog.color.setHex(nextHex);
        },
    };
}
