const THREE = window.THREE;

export const SKY_COLOR = 0x87ceeb;

let wasmSkyModule;
let wasmSkyReady = false;

async function ensureWasmSkyLoaded() {
    if (wasmSkyReady) return wasmSkyModule;
    try {
        // Generated by wasm-pack / wasm-bindgen for src/sky crate.
        const module = await import('./pkg/bevy_sky_gradient.js');
        if (typeof module.default === 'function') {
            await module.default();
        }
        wasmSkyModule = module;
        wasmSkyReady = true;
        return wasmSkyModule;
    } catch (_error) {
        wasmSkyReady = true;
        wasmSkyModule = null;
        return null;
    }
}

export function applySkyAtmosphere(scene) {
    scene.background = new THREE.Color(SKY_COLOR);
    scene.fog = new THREE.Fog(SKY_COLOR, 20, 60);

    ensureWasmSkyLoaded();

    return {
        update(timeSeconds) {
            if (!wasmSkyModule || typeof wasmSkyModule.sky_color_hex !== 'function') return;
            const nextHex = wasmSkyModule.sky_color_hex(timeSeconds);
            scene.background.setHex(nextHex);
            scene.fog.color.setHex(nextHex);
        },
    };
}
